Set virtual display background colour with argument

diff --git a/pt-web-vnc b/pt-web-vnc
--- a/pt-web-vnc
+++ b/pt-web-vnc
@@ -22,6 +22,13 @@ start_xvfb() {
     Xvfb ":${DISPLAY_ID}" -screen 0 "${SCREEN_WIDTH}x${SCREEN_HEIGHT}x${SCREEN_DEPTH}" &
     echo "Xvfb PID is $!"
     PIDS+=("$!")
+
+    sleep 2
+}
+
+
+set_background_colour() {
+    xsetroot -solid "${BACKGROUND_COLOUR}" -d ":${DISPLAY_ID}"
 }
 
 
@@ -94,13 +101,12 @@ create_pid_file() {
 
 
 start_window_manager() {
-    sleep 2
     eval "DISPLAY=:${DISPLAY_ID} bspwm &"
     PIDS+=("$!")
     sleep 2
 
     # Custom rule to handle 'wpa_gui'
-    DISPLAY=:"${DISPLAY_ID}" bspc rule -a wpa_gui state=pseudo_tiled
+    DISPLAY=:"${DISPLAY_ID}" bspc rule -a wpa_gui state=tiled
 }
 
 
@@ -120,7 +126,12 @@ do_start() {
 
     # Load window manager if requested
     if [ -n "${USE_WINDOW_MANAGER}" ]; then
-        start_window_manager
+        start_window_manager || (kill_pids && exit 1)
+    fi
+
+    # Set background colour
+    if [ -n "${BACKGROUND_COLOUR}" ]; then
+        set_background_colour || echo "Couldn't set the background colour to '${BACKGROUND_COLOUR}"
     fi
 
     # Run provided command
@@ -158,7 +169,7 @@ get_url() {
 
 
 usage() {
-  echo -e "Usage:\n\tpt-web-vnc <COMMAND> --display_id <DISPLAY_ID> --HEIGHT <SCREEN_HEIGHT> --WIDTH <SCREEN_WIDTH> --ssl_certificate <SSL_CERTIFICATE> --window_title <WINDOW_TITLE> --run <RUN_COMMAND>"
+  echo -e "Usage:\n\tpt-web-vnc <COMMAND> --display_id <DISPLAY_ID> --HEIGHT <SCREEN_HEIGHT> --WIDTH <SCREEN_WIDTH> --ssl_certificate <SSL_CERTIFICATE> --window_title <WINDOW_TITLE> --run <RUN_COMMAND> --background-colour <COLOUR>"
   echo "where:"
   echo -e "\tCOMMAND: start, stop, url."
   echo -e "\tDISPLAY_ID: integer, id for the display to use/create."
@@ -167,6 +178,7 @@ usage() {
   echo -e "\tSSL_CERTIFICATE: path to combined SSL certificate & key file. Optional."
   echo -e "\tWINDOW_TITLE: Title of a window in a display to share over VNC. Optional."
   echo -e "\tRUN_COMMAND: Command to run before starting VNC server."
+  echo -e "\tCOLOUR: string with a colour name to use as background for the virtual display."
 }
 
 
@@ -180,9 +192,10 @@ SCREEN_HEIGHT="1080"
 SCREEN_WIDTH="1920"
 SCREEN_DEPTH="24"
 USE_WINDOW_MANAGER=""
+BACKGROUND_COLOUR=""
 
 # Parse options
-VALID_ARGS="$(getopt -o w:i:s:r:v:o:d:mh --long window_title:,display_id:,ssl_certificate:,run:,height:,width:,depth:,with-window-manager,help --name pt-web-vnc -- "$@")"
+VALID_ARGS="$(getopt -o w:i:s:r:v:o:d:b:mh --long window_title:,display_id:,ssl_certificate:,run:,height:,width:,depth:,background-colour:,with-window-manager,help --name pt-web-vnc -- "$@")"
 if [[ $? -ne 0 ]]; then
     usage
     exit 1;
@@ -220,6 +233,10 @@ while [ : ]; do
             ;;
         -r | --run)
             RUN_COMMAND="${2}"
+            shift 2
+            ;;
+        -b | --background-colour)
+            BACKGROUND_COLOUR="${2}"
             shift 2
             ;;
         -m | --with-window-manager)
